CREATE DATABASE IF NOT EXISTS mqttJS;

USE mqttJS;

CREATE TABLE IF NOT EXISTS mqttjs (
  id INT(11) NOT NULL AUTO_INCREMENT,
  message VARCHAR(255) DEFAULT NULL,
  time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '';
